version: "3.9"

services:
  dev_db:
    image: postgres:15.3-alpine
    container_name: pushup.dev_db
    restart: unless-stopped
    networks:
      - pushup
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: local
      POSTGRES_DB: dev
    volumes:
      - .postgres-data:/var/lib/postgresql/data
    ports:
      - 5435:5432

  api:
    container_name: pushup.api
    user: 1000:1000 # for linux to delete created files
    tty: true
    environment:
      BUILD_ENV: local
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: pushup-backend
    ports:
      - 8100:8000
    networks:
      - pushup
    restart: always
    volumes:
      - .:/opt/pushupclub
    depends_on:
      - dev_db

networks:
  pushup:
    driver: bridge

volumes:
  postgres-data:
